language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  jobs:
    - CD="playbooks/replicaset" SCENARIO="default"
    - CD="playbooks/replicaset" SCENARIO="debian"
    - CD="playbooks/sharded_cluster" SCENARIO="default"
    - CD="playbooks/sharded_cluster" SCENARIO="debian"
before_install:
  - python --version
  - pip install --upgrade pip
  - export pyv=$(python -c 'from platform import python_version; print(python_version()[:3])')
  - pip install --requirement requirements-${pyv}.txt
  - ansible-galaxy collection install community.general
  - wget https://github.com/ansible-collections/community.mongodb/releases/download/refs%2Fheads%2Fmaster/community-mongodb-latest.tar.gz
  - ansible-galaxy collection install community-mongodb-latest.tar.gz
  - pip --version
  - ansible --version
  - molecule --version
  - pytest --version
script:
  - cd "$CD"
  #- export ANSIBLE_STRATEGY=mitogen_linear
  #- export ANSIBLE_STRATEGY_PLUGINS=${VIRTUAL_ENV}/lib/python${TRAVIS_PYTHON_VERSION}/site-packages/ansible_mitogen/plugins/strategy
  - travis_wait 50 molecule test --scenario-name "$SCENARIO"
after_success:
  - codecov
