language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - PY="/usr/libexec/platform-python" CD="playbooks/replicaset" SCENARIO="default"
  - PY="/usr/bin/python" CD="playbooks/replicaset" SCENARIO="debian"
  - PY="/usr/libexec/platform-python" CD="playbooks/sharded_cluster" SCENARIO="default"
  - PY="/usr/bin/python" CD="playbooks/sharded_cluster" SCENARIO="debian"
before_install:
  - python --version
  - pip install --upgrade pip
  - export pyv=$(python -c 'from platform import python_version; print(python_version()[:3])')
  - pip install --requirement requirements-${pyv}.txt
  - ansible-galaxy collection install community.general
  - wget https://github.com/ansible-collections/community.mongodb/releases/download/refs%2Fheads%2Fmaster/community-mongodb-latest.tar.gz
  - ansible-galaxy collection install community-mongodb-latest.tar.gz
  - pip --version
  - ansible --version
  - molecule --version
  - pytest --version
script:
  #- export ANSIBLE_VAULT_PASSWORD_FILE="$(pwd)/playbooks/replicaset/molecule/default/.vault_pass.txt"
  - export ANSIBLE_PYTHON_INTERPRETER="$PY"  # Could go in molecule.yml
  - cd "$CD"
  - molecule test --scenario-name "$SCENARIO"
after_success:
  - codecov # submit coverage
