---
- name: Create custom role file
  copy:
    content: |
      db.dropRole("compactLocal", { w: "majority" });
      db.createRole(
      {
        role: "compactLocal",
        privileges: [
        {
            resource: { "db" : "local" , "collection" : "oplog.rs" },
            actions: [ "compact" ]
         }
         ],
         roles: []
       }
      );
    dest: mongodb_role.js

- name: Run role file via the cmd line
  shell: mongo admin --host {{ rs }}/localhost:{{ mongod_port }} --username {{ admin_user }} --password {{ admin_user_password }} mongodb_role.js && touch compact_role.success
  args:
    creates: compact_role.success
  run_once: yes

- name: Add compactLocal role to user
  community.mongodb.mongodb_user:
    login_host: localhost
    login_port: "{{ mongod_port }}"
    login_user: "{{ admin_user }}"
    login_password: "{{ admin_user_password }}"
    database: admin
    replica_set: "{{ rs }}"
    name: "{{ admin_user }}"
    password: "{{ admin_user_password }}"
    roles:
      - root
      - compactLocal
    state: present
    update_password: on_create
  run_once: yes
