---
  version: "3.8"
  services:
    mongodb1:
      hostname: "mongodb1"
      container_name: "mongodb1"
      image: "mongo:latest"
      ports:
        - "27017:27017"
      volumes:
        - ./startup_scripts:/docker-entrypoint-initdb.d
        - "mongodb1"
        - "./file.key:/data/file.key"
        - "./bash/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      networks:
        - "mongonet"
      depends_on:
        - "mongodb2"
        - "mongodb3"
    mongodb2:
      hostname: "mongodb2"
      container_name: "mongodb2"
      image: "mongo:latest"
      ports:
        - "27018:27017"
      volumes:
        - "mongodb2"
        - "./file.key:/data/file.key"
        - "./bash/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      networks:
        - "mongonet"
    mongodb3:
      hostname: "mongodb3"
      container_name: "mongodb3"
      image: "mongo:latest"
      ports:
        - "27019:27017"
      volumes:
        - "mongodb3"
        - "./file.key:/data/file.key"
        - "./bash/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      networks:
        - "mongonet"
  volumes:
    mongodb1: {}
    mongodb2: {}
    mongodb3: {}
  networks:
    mongonet: {}
