---
  version: "3.8"
  services:
    s1-mongodb1:
      hostname: "s1-mongodb1"
      container_name: "s1-mongodb1"
      image: "mongo:latest"
      ports:
        - "27017:27017"
      volumes:
        - ./startup_scripts:/docker-entrypoint-initdb.d
        - "s1-mongodb1"
        - "./file.key:/data/file.key"
        - "./bash/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      networks:
        - "shardnet"
      depends_on:
        - "s1-mongodb2"
        - "s1-mongodb3"
    s1-mongodb2:
      hostname: "s1-mongodb2"
      container_name: "s1-mongodb2"
      image: "mongo:latest"
      ports:
        - "27018:27017"
      volumes:
        - "s1-mongodb2"
        - "./file.key:/data/file.key"
        - "./bash/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      networks:
        - "shardnet"
    s1-mongodb3:
      hostname: "s1-mongodb3"
      container_name: "s1-mongodb3"
      image: "mongo:latest"
      ports:
        - "27019:27017"
      volumes:
        - "s1-mongodb3"
        - "./file.key:/data/file.key"
        - "./bash/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      networks:
        - "shardnet"
    s2-mongodb4:
    s2-mongodb5:
    s2-mongodb6:
    mongos1:
    mongos2:
    mongos3:
  volumes:
    s1-mongodb1: {}
    s1-mongodb2: {}
    s1-mongodb3: {}
    s2-mongodb4: {}
    s2-mongodb5: {}
    s2-mongodb6: {}
  networks:
    shardnet: {}
