---
  version: "3.8"
  services:
    mongodb:
      image: "mongo:latest"
      ports:
        - "27017:27017"
      volumes:
        - "mongodb"
      env_file:
        - mongodb-admin-user.env
  volumes:
    mongodb: {}
