---
- hosts: mongodb
  gather_facts: yes
  vars_files:
    - ./vault.yml
  roles:
    - role: "community.mongodb.mongodb_linux"
    - role: "community.mongodb.mongodb_selinux"
    - role: "community.mongodb.mongodb_repository"
    - { role: "community.mongodb.mongodb_mongod", sharding: true, mongod_port: 27018 }

  tasks:

    - name: Ensure pymongo is installed
      pip:
        name: pymongo
        state: present

    - name: Ensure mongo shell is installed
      package:
        name: mongodb-org-shell
        state: present

    - name: Setup replicasets
      include_tasks: replicaset.yml
      vars:
        mongod_port: 27018
      when: ansible_hostname in ["mongodb1", "mongodb4"]
