---
- hosts: all
  gather_facts: yes
  become: yes
  serial: 1
  vars_files:
    - ../vars/main.yml
    - ../replicaset/vault.yml
  vars:
    required_packages:
      - "yum-plugin-versionlock"

  tasks:

    - name: Ensure required packages are installed
      yum:
        name: yum-plugin-versionlock
      when: ansible_os_family == "RedHat"

    - name: Ensure mongodb-org* packages are version locked
      shell: yum versionlock mongodb-org* && touch /root/mongo_version_lock.success
      args:
        creates: /root/mongo_version_lock.success
      when: ansible_os_family == "RedHat"

    - import_tasks: ../shared_tasks/get_primary.yml

    - name: Patch SECONARY MongoDB hosts first
      block:
        - import_tasks: ../shared_tasks/patch_os.yml
      when: inventory_hostname_short != primary

- hosts: all
  gather_facts: yes
  become: yes
  vars_files:
    - ../vars/main.yml
    - ../replicaset/vault.yml

  tasks:

    - import_tasks: ../shared_tasks/get_primary.yml

    - name: Patch PRIMARY MongoDB Host
      block:
        - import_tasks: ../shared_tasks/patch_os.yml
      when: inventory_hostname_short == primary
