---
- hosts: all
  gather_facts: yes
  vars_files:
    - ./vault.yml
  roles:
    - role: "community.mongodb.mongodb_linux"
    - role: "community.mongodb.mongodb_selinux"
    - role: "community.mongodb.mongodb_repository"
    - role: "community.mongodb.mongodb_mongod"

  tasks:

    - name: Ensure pymongo is installed
      pip:
        name: pymongo
        state: present

    - name: Ensure mongo shell is installed
      package:
        name: mongodb-org-shell
        state: present

    - name: Initialise MongoDB Replicaset
      community.mongodb.mongodb_replicaset:
        login_database: "admin"
        login_host: localhost
        members:
          - mongodb1.local:27017
          - mongodb2.local:27017
          - mongodb3.local:27017
      register: create_rs
      when: groups.mongodb.index(inventory_hostname) == 0

    - pause:
        seconds: 10
      when: create_rs.changed == true

    - name: Has MongoDB Admin User been created already?
      stat:
        path: /root/mongodb_admin.success
      when: groups.mongodb.index(inventory_hostname) == 0
      register: mongodb_admin

    - debug:
        var: mongodb_admin

    - name: Add MongoDB Admin User using localhost exception
      community.mongodb.mongodb_user:
        name: "{{ admin_user }}"
        password: "{{ admin_user_password }}"
        database: admin
        roles:
          - "root"
      when:
        - groups.mongodb.index(inventory_hostname) == 0
        - mongodb_admin.stat.exists == False

    - shell: "mongo admin --username {{ admin_user }} --password {{ admin_user_password }} --eval 'db.runCommand({listDatabases: 1})' && touch /root/mongodb_admin.success"
      args:
        creates: /root/mongodb_admin.success
      when:
        - groups.mongodb.index(inventory_hostname) == 0
        - mongodb_admin.stat.exists == False
      ignore_errors: yes

    - name: Has MongoDB App Users been created already?
      stat:
        path: /root/mongodb_users.success
      when: groups.mongodb.index(inventory_hostname) == 0
      register: mongodb_users

    - name: Add MongoDB App Users
      community.mongodb.mongodb_user:
        login_user: "{{ admin_user }}"
        login_password: "{{ admin_user_password }}"
        login_database: admin
        user: "{{ item.username }}"
        password: "{{ item.password }}"
        database: "{{ item.database }}"
        roles: "{{ item.roles }}"
        replica_set: rs0
      with_items:
        - "{{ app_users }}"
      when:
        - groups.mongodb.index(inventory_hostname) == 0
        - mongodb_users.stat.exists == False
      no_log: yes

    - shell: "mongo {{ item.database }} --username {{ item.username }} --password {{ item.password }} --eval 'db.runCommand({listCollections: 1})' && touch /root/mongodb_users.success"
      args:
        creates: /root/mongodb_users.success
      when:
        - groups.mongodb.index(inventory_hostname) == 0
        - mongodb_users.stat.exists == False
      with_items:
        - "{{ app_users }}"
      no_log: yes
      ignore_errors: yes
