---
galaxy_info:
  author: Rhys Campbell
  description: A simple role providing MongoDB repository setup for RedHat, Debian and Ubuntu platforms.
  platforms:
    - name: RedHat
      versions:
      - all
    - name: Debian
      versions:
      - all
    - name: Ubuntu
      versions:
      - all

  galaxy_tags:
    - mongodb
