name: CI
on:
  pull_request:
  schedule:
    - cron: "0 3 * * *"

jobs:
  standalone:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AutomatingMongoDBWithAnsible
    strategy:
      matrix:
        python_version:
          - "3.6"
          - "3.7"
          - "3.8"
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: AutomatingMongoDBWithAnsible

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Run CI_Setup.sh script
        run: .github/bash/CI_Setup.sh

      - name: Run standalone playbook
        run: |
          ansible-playbook \
                --become \
                --connection=local \
                --inventory 127.0.0.1, \
                --limit 127.0.0.1 mongodb.yml -i ansible_hosts
        working-directory: AutomatingMongoDBWithAnsible/playbooks/standalone
        env:
          ANSIBLE_VAULT_PASSWORD_FILE: "../../.vault_pass.txt"

  replicaset:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AutomatingMongoDBWithAnsible
    strategy:
      matrix:
        python_version:
          - "3.6"
          - "3.7"
          - "3.8"
        molecule_scenario:
          - "default"
          - "debian"
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: AutomatingMongoDBWithAnsible

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Run CI_Setup.sh script
        run: .github/bash/CI_Setup.sh

      - name: Run molecule test for scenario ${{ matrix.molecule_scenario }}
        run: molecule test --scenario-name ${{ matrix.molecule_scenario }}
        working-directory: AutomatingMongoDBWithAnsible/playbooks/replicaset

  sharded_cluster:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AutomatingMongoDBWithAnsible
    strategy:
      matrix:
        python_version:
          - "3.6"
          - "3.7"
          - "3.8"
        molecule_scenario:
          - "default"
          - "debian"
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: AutomatingMongoDBWithAnsible

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Run CI_Setup.sh script
        run: .github/bash/CI_Setup.sh

      - name: Run molecule test for scenario ${{ matrix.molecule_scenario }}
        run: molecule test --scenario-name ${{ matrix.molecule_scenario }}
        working-directory: AutomatingMongoDBWithAnsible/playbooks/sharded_cluster

  upgrade_replicaset:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AutomatingMongoDBWithAnsible
    strategy:
      matrix:
        python_version:
          - "3.6"
          - "3.7"
          - "3.8"
        molecule_scenario:
          - "default"
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: AutomatingMongoDBWithAnsible

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Run CI_Setup.sh script
        run: .github/bash/CI_Setup.sh

      - name: Run molecule converge for scenario ${{ matrix.molecule_scenario }}
        run: molecule converge --scenario-name ${{ matrix.molecule_scenario }}
        working-directory: AutomatingMongoDBWithAnsible/playbooks/replicaset

      - name: Get container names for the inventory file
        run: docker ps | awk '{print $NF}' | grep mongo > mongo_inventory.inv
        working-directory: AutomatingMongoDBWithAnsible/playbooks/maintenance

      - name: Install sudo in docker
        run: ansible all -i mongo_inventory.inv -c docker -m raw -a "yum install sudo -y"
        working-directory: AutomatingMongoDBWithAnsible/playbooks/maintenance

      - name: Run upgrade playbook
        run: ansible-playbook -i mongo_inventory.inv -c docker --skip-tags reboot --tags all,never  mongodb_replicaset_upgrade.yml
        working-directory: AutomatingMongoDBWithAnsible/playbooks/maintenance
        env:
          ANSIBLE_VAULT_PASSWORD_FILE: "../../.vault_pass.txt"

  upgrade_sharded_cluster:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AutomatingMongoDBWithAnsible
    strategy:
      matrix:
        python_version:
          - "3.6"
          - "3.7"
          - "3.8"
        molecule_scenario:
          - "default"
          - "debian"
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: AutomatingMongoDBWithAnsible

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Run CI_Setup.sh script
        run: .github/bash/CI_Setup.sh

      - name: Run molecule test for scenario ${{ matrix.molecule_scenario }}
        run: molecule test --scenario-name ${{ matrix.molecule_scenario }}
        working-directory: AutomatingMongoDBWithAnsible/playbooks/sharded_cluster

      - name: Write inventory file for cluster
        uses: DamianReeves/write-file-action
        with:
          path: AutomatingMongoDBWithAnsible/playbooks/maintenance/mongo_inventory.inv
          contents: |
            [mongodb]
            mongodb1
            mongodb2
            mongodb3
            mongodb4
            mongodb5
            mongodb6

            [rs0]
            mongodb1
            mongodb2
            mongodb3

            [rs1]
            mongodb4
            mongodb5
            mongodb6

            [mongos]
            mongos1
            mongos2
            mongos3
          write-mode: overwrite

      - name: Install sudo in docker
        run: ansible all -i mongo_inventory.inv -c docker -m raw -a "yum install sudo -y"
        working-directory: AutomatingMongoDBWithAnsible/playbooks/maintenance

      - name: Run upgrade playbook
        run: ansible-playbook -i mongo_inventory.inv -c docker --skip-tags reboot --tags all,never  mongodb_sharded_cluster_upgrade.yml
        working-directory: AutomatingMongoDBWithAnsible/playbooks/maintenance
        env:
          ANSIBLE_VAULT_PASSWORD_FILE: "../../.vault_pass.txt"
