name: CI
on:
  - pull_request

jobs:
  standalone:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AutomatingMongoDBWithAnsible
    strategy:
      matrix:
        python_version:
          - "3.6"
          - "3.7"
          - "3.8"
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: AutomatingMongoDBWithAnsible

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Run CI_Setup.sh script
        run: .github/bash/CI_Setup.sh

      - name: Run stanadalone playbook
        run: |
          ansible-playbook \
                --become \
                --connection=local \
                --inventory 127.0.0.1, \
                --limit 127.0.0.1 mongodb.yml -i ansible_hosts
        working-directory: AutomatingMongoDBWithAnsible/playbooks/standalone
        env:
          ANSIBLE_VAULT_PASSWORD_FILE: "../../.vault_pass.txt"

  replicaset:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AutomatingMongoDBWithAnsible
    strategy:
      matrix:
        python_version:
          - "3.6"
          - "3.7"
          - "3.8"
        molecule_scenario:
          - "default"
          - "debian"
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: AutomatingMongoDBWithAnsible

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Run CI_Setup.sh script
        run: .github/bash/CI_Setup.sh

      - name: Run molecule test for scenario ${{ matrix.molecule_scenario }}
        run: molecule test --scenario-name ${{ matrix.molecule_scenario }}
        working-directory: AutomatingMongoDBWithAnsible/playbooks/replicaset

  sharded_cluster:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AutomatingMongoDBWithAnsible
    strategy:
      matrix:
        python_version:
          - "3.6"
          - "3.7"
          - "3.8"
        molecule_scenario:
          - "default"
          - "debian"
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: AutomatingMongoDBWithAnsible

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Run CI_Setup.sh script
        run: .github/bash/CI_Setup.sh

      - name: Run molecule test for scenario ${{ matrix.molecule_scenario }}
        run: molecule test --scenario-name ${{ matrix.molecule_scenario }}
        working-directory: AutomatingMongoDBWithAnsible/playbooks/sharded_cluster
